export default {
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1f391b9e": [() => import(/* webpackChunkName: "1f391b9e" */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  "265ae853": [() => import(/* webpackChunkName: "265ae853" */ "/Users/gustavgullstrand/Development/woodlanddev/organicmakers/app/public/wp-content/plugins/artisan-sale-manager/website/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json"), "/Users/gustavgullstrand/Development/woodlanddev/organicmakers/app/public/wp-content/plugins/artisan-sale-manager/website/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/gustavgullstrand/Development/woodlanddev/organicmakers/app/public/wp-content/plugins/artisan-sale-manager/website/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json")],
  "5b5b5b1d": [() => import(/* webpackChunkName: "5b5b5b1d" */ "@site/docs/features/shortcodes.md"), "@site/docs/features/shortcodes.md", require.resolveWeak("@site/docs/features/shortcodes.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "935f2afb": [() => import(/* webpackChunkName: "935f2afb" */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "c5e3162a": [() => import(/* webpackChunkName: "c5e3162a" */ "@site/src/pages/pricing.md"), "@site/src/pages/pricing.md", require.resolveWeak("@site/src/pages/pricing.md")],
  "f0f73323": [() => import(/* webpackChunkName: "f0f73323" */ "/Users/gustavgullstrand/Development/woodlanddev/organicmakers/app/public/wp-content/plugins/artisan-sale-manager/website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json"), "/Users/gustavgullstrand/Development/woodlanddev/organicmakers/app/public/wp-content/plugins/artisan-sale-manager/website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/gustavgullstrand/Development/woodlanddev/organicmakers/app/public/wp-content/plugins/artisan-sale-manager/website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json")],};
